Change config from toml to yaml
darwinia-network/bridger pull request #147
Opened 2021-01-25 04:03 UTC by wuminzhe

2021-01-27 13:52 UTC, xiaoch05 commented
I recommend that we separate the configures of d2e and e2d in the configure file if some item is used by only one of them.

2021-02-01 07:09 UTC, wuminzhe commented
@xiaoch05 I did this before like what you said, but after discussion, they were moved to ethereum and darwinia section.

2021-02-01 08:41 UTC, wuminzhe commented on src/service/ethereum.rs
>  		.map(|c| {
the code changed here(310~322) need to be reviewed carefully

2021-02-02 06:08 UTC, xiaoch05 approved these changes

2021-02-03 10:09 UTC, HackFisher requested changes

2021-02-03 10:09 UTC, HackFisher commented on .maintain/config/mainnet.sample.yml
> +  rpc: wss://crab.darwinia.network
Need to update the rpc to correct one, not crab

2021-02-04 05:04 UTC, HackFisher approved these changes

2021-02-04 05:04 UTC, merged