Bump v0.5.2
darwinia-network/bridger pull request #424
Opened 2022-03-07 09:02 UTC by fewensa

Just tag the new version. and wait for new release for darwinia-common project.

2022-03-08 10:45 UTC, fewensa commented on thegraph/mmr/subgraph-ropsten.yaml
> +      startBlock: 14288600
Please help to check `startBlock` is right? @xiaoch05

2022-03-08 10:45 UTC, fewensa commented on thegraph/mmr/subgraph-ropsten.yaml
> +      startBlock: 14288600
Also check ethereum subgraph

2022-03-11 05:11 UTC, fewensa commented on thegraph/mmr/src/mapping.ts
> +  for (const item of records) {
@xiaoch05 Please check there

2022-03-11 06:07 UTC, fewensa commented
About wrong Ropsten chain hash index by theGraph,  please follow https://github.com/graphprotocol/indexer/issues/379

2022-03-11 07:36 UTC, fewensa commented
https://github.com/darwinia-network/bridger/pull/424/commits/33aa26600a01c29b957bac63e0f369f689a68c89

fix the wrong condition for #286 

https://github.com/darwinia-network/bridger/pull/286/files#diff-c1bbb0a9e23066475d24431617d8515ca11d65e3a4bf7546e36f532b1b670ec2R11

2022-03-11 08:13 UTC, xiaoch05 approved these changes

2022-03-11 08:52 UTC, HackFisher requested changes
Hold on and let's do the upgration first.

2022-03-11 10:14 UTC, merged