Cache start
darwinia-network/bridger pull request #88
Opened 2020-11-12 02:19 UTC by wuminzhe

1. run --data-dir <dir>
2. cache start

2020-11-13 03:25 UTC, HackFisher commented
@wuminzhe Can we automatically update the start according to the latest redeemed tx? Seems we can only set the start manually in this PR?

2020-11-13 03:44 UTC, wuminzhe commented
@HackFisher it take ethereum lastest block as start if not cache not exist. and save the last scanned block to cache after a scan.

2020-11-13 03:58 UTC, HackFisher commented
> @HackFisher it take ethereum lastest block as start if cache not exist. and save the last scanned block to cache after a scan.

I think we should use last redeemed tx block as start, not the latest scanned block number.

Using latest scanned block number introduce possibilities that we might miss some ethereum tx which need redeem.

2020-11-13 03:59 UTC, wuminzhe commented
yes, I will change it to the last redeemed tx block

2020-11-13 05:36 UTC, wuminzhe commented
@HackFisher  last redeemed tx from chain or local?

2020-11-16 05:14 UTC, HackFisher requested changes
@wuminzhe Please update the sample config files in .maintain too, thanks

2020-11-16 05:14 UTC, HackFisher commented on src/service/redeem.rs
> +    /// get_ethereum_start
update comment

2020-11-16 05:14 UTC, HackFisher commented on src/service/redeem.rs
> +    /// set_ethereum_start
update comment

2020-11-16 05:58 UTC, HackFisher approved these changes

2020-11-16 05:58 UTC, merged