add receipt api
darwinia-network/bridger pull request #98
Opened 2020-12-16 02:26 UTC by xiaoch05

bridger-primitives need to support an API for getting receipt information.
for issue https://github.com/darwinia-network/shadow/issues/114

2020-12-17 06:59 UTC, HackFisher requested changes

2020-12-17 06:59 UTC, HackFisher commented on primitives/src/chain/ethereum/header.rs
> +    pub transactions: Vec<String>,
transactions should not be part of Header?

2020-12-17 07:14 UTC, xiaoch05 commented on primitives/src/chain/ethereum/header.rs
> +    pub transactions: Vec<String>,
There is no API for getting Header. So this Header means Block. do we need to change it to Block struct?

2020-12-17 07:27 UTC, HackFisher commented on primitives/src/chain/ethereum/header.rs
> +    pub transactions: Vec<String>,
EthHeaderRPCResp 和 EthereumHeaderRPC改成Block，但是EthereumHeaderJson 或 EthereumHeader是Header的意思，其他使用的地方是按照Header来消费的，不应该改成Block或者增加transactions

2020-12-21 07:23 UTC, HackFisher approved these changes

2020-12-21 07:23 UTC, merged